//@version=5
indicator("Cross Dashboard", overlay=true)

// Input fields for EMA lengths
ema9_length = input.int(9, title="Length for EMA 9", minval=1)
ema15_length = input.int(15, title="Length for EMA 15", minval=1)
ema20_length = input.int(20, title="Length for EMA 20", minval=1)
ema50_length = input.int(50, title="Length for EMA 50", minval=1)
ema200_length = input.int(200, title="Length for EMA 200", minval=1)

ema9 = ta.ema(close, ema9_length)
ema15 = ta.ema(close, ema15_length)
ema20 = ta.ema(close, ema20_length)
ema50 = ta.ema(close, ema50_length)
ema200 = ta.ema(close, ema200_length)


cross15 = ema9 > ema15 ? "Bullish" : "Bearish"
cross9 = ema9 > ema20 ? "Bullish" : "Bearish"
cross20 = ema20 > ema50 ? "Bullish" : "Bearish"
cross50 = ema50 > ema200 ? "Bullish" : "Bearish"

// Define colors for dashboard
colorshortshort = ema9 > ema15 ? color.green : color.red
colorshort = ema9 > ema20 ? color.green : color.red
colorminidum = ema20 > ema50 ? color.green : color.red
colorlong = ema50 > ema200 ? color.green : color.red

// Create table with the correct number of rows
var table dashboard = table.new(position=position.top_right, frame_color=color.black, border_color=color.black, columns=2, rows=17, border_width=1)

// Update table values
table.cell(dashboard, 0, 0, "9 > 15", text_color=color.white, bgcolor=color.black)
table.cell(dashboard, 1, 0, cross15, text_color=color.white, bgcolor=colorshortshort)
table.cell(dashboard, 0, 1, "9 > 20", text_color=color.white, bgcolor=color.black)
table.cell(dashboard, 1, 1, cross9, text_color=color.white, bgcolor=colorshort)
table.cell(dashboard, 0, 2, "20 > 50", text_color=color.white, bgcolor=color.black)
table.cell(dashboard, 1, 2, cross20, text_color=color.white, bgcolor=colorminidum)
table.cell(dashboard, 0, 3, "50 > 200", text_color=color.white, bgcolor=color.black)
table.cell(dashboard, 1, 3, cross50, text_color=color.white, bgcolor=colorlong)