//@version=5
indicator("Cross Dashboard", overlay=true)

// Input fields for EMA lengths
ema1_length = input.int(1, title="Length for EMA 1", minval=1)
ema2_length = input.int(2, title="Length for EMA 2", minval=1)
ema3_length = input.int(3, title="Length for EMA 3", minval=1)
ema4_length = input.int(4, title="Length for EMA 4", minval=1)
ema5_length = input.int(5, title="Length for EMA 5", minval=1)
ema6_length = input.int(6, title="Length for EMA 6", minval=1)
ema7_length = input.int(7, title="Length for EMA 7", minval=1)
ema8_length = input.int(8, title="Length for EMA 8", minval=1)
ema9_length = input.int(9, title="Length for EMA 9", minval=1)
ema10_length = input.int(10, title="Length for EMA 10", minval=1)
ema11_length = input.int(11, title="Length for EMA 11", minval=1)
ema12_length = input.int(12, title="Length for EMA 12", minval=1)
ema13_length = input.int(13, title="Length for EMA 13", minval=1)
ema14_length = input.int(14, title="Length for EMA 14", minval=1)
ema15_length = input.int(15, title="Length for EMA 15", minval=1)

ema20_length = input.int(20, title="Length for EMA 20", minval=1)
ema50_length = input.int(50, title="Length for EMA 50", minval=1)
ema200_length = input.int(200, title="Length for EMA 200", minval=1)

// Define EMAs
ema1 = ta.ema(close, ema1_length)
ema2 = ta.ema(close, ema2_length)
ema3 = ta.ema(close, ema3_length)
ema4 = ta.ema(close, ema4_length)
ema5 = ta.ema(close, ema5_length)
ema6 = ta.ema(close, ema6_length)
ema7 = ta.ema(close, ema7_length)
ema8 = ta.ema(close, ema8_length)
ema9 = ta.ema(close, ema9_length)
ema10 = ta.ema(close, ema10_length)
ema11 = ta.ema(close, ema11_length)
ema12 = ta.ema(close, ema12_length)
ema13 = ta.ema(close, ema13_length)
ema14 = ta.ema(close, ema14_length)
ema15 = ta.ema(close, ema15_length)

ema20 = ta.ema(close, ema20_length)
ema50 = ta.ema(close, ema50_length)
ema200 = ta.ema(close, ema200_length)

// Define cross conditions
cross1 = ema1 > ema2 ? "Bullish" : "Bearish"
cross2 = ema2 > ema3 ? "Bullish" : "Bearish"
cross3 = ema3 > ema4 ? "Bullish" : "Bearish"
cross4 = ema4 > ema5 ? "Bullish" : "Bearish"
cross5 = ema5 > ema6 ? "Bullish" : "Bearish"
cross6 = ema6 > ema7 ? "Bullish" : "Bearish"
cross7 = ema7 > ema8 ? "Bullish" : "Bearish"
cross8 = ema8 > ema9 ? "Bullish" : "Bearish"
cross9 = ema9 > ema10 ? "Bullish" : "Bearish"
cross10 = ema10 > ema11 ? "Bullish" : "Bearish"
cross11 = ema11 > ema12 ? "Bullish" : "Bearish"
cross12 = ema12 > ema13 ? "Bullish" : "Bearish"
cross13 = ema13 > ema14 ? "Bullish" : "Bearish"
cross14 = ema14 > ema15 ? "Bullish" : "Bearish"


crossshort = ema9 > ema20 ? "Bullish" : "Bearish"
cross20 = ema20 > ema50 ? "Bullish" : "Bearish"
cross50 = ema50 > ema200 ? "Bullish" : "Bearish"

// Define colors for dashboard
color1 = ema1 > ema2 ? color.green : color.red
color2 = ema2 > ema3 ? color.green : color.red
color3 = ema3 > ema4 ? color.green : color.red
color4 = ema4 > ema5 ? color.green : color.red
color5 = ema5 > ema6 ? color.green : color.red
color6 = ema6 > ema7 ? color.green : color.red
color7 = ema7 > ema8 ? color.green : color.red
color8 = ema8 > ema9 ? color.green : color.red
color9 = ema9 > ema10 ? color.green : color.red
color10 = ema10 > ema11 ? color.green : color.red
color11 = ema11 > ema12 ? color.green : color.red
color12 = ema12 > ema13 ? color.green : color.red
color13 = ema13 > ema14 ? color.green : color.red
color14 = ema14 > ema15 ? color.green : color.red

colorshort = ema9 > ema20 ? color.green : color.red
colorminidum = ema20 > ema50 ? color.green : color.red
colorlong = ema50 > ema200 ? color.green : color.red

// Create table
var table dashboard = table.new(position=position.top_right, frame_color=color.black, border_color=color.black, columns=2, rows=14, border_width=1)

// Update table values
table.cell(dashboard, 0, 0, "1 > 2", text_color=color.white, bgcolor=color1)
table.cell(dashboard, 1, 0, cross1, text_color=color.white, bgcolor=color1)
table.cell(dashboard, 0, 1, "2 > 3", text_color=color.white, bgcolor=color2)
table.cell(dashboard, 1, 1, cross2, text_color=color.white, bgcolor=color2)
table.cell(dashboard, 0, 2, "3 > 4", text_color=color.white, bgcolor=color3)
table.cell(dashboard, 1, 2, cross3, text_color=color.white, bgcolor=color3)
table.cell(dashboard, 0, 3, "4 > 5", text_color=color.white, bgcolor=color4)
table.cell(dashboard, 1, 3, cross4, text_color=color.white, bgcolor=color4)
table.cell(dashboard, 0, 4, "5 > 6", text_color=color.white, bgcolor=color5)
table.cell(dashboard, 1, 4, cross5, text_color=color.white, bgcolor=color5)
table.cell(dashboard, 0, 5, "6 > 7", text_color=color.white, bgcolor=color6)
table.cell(dashboard, 1, 5, cross6, text_color=color.white, bgcolor=color6)
table.cell(dashboard, 0, 6, "7 > 8", text_color=color.white, bgcolor=color7)
table.cell(dashboard, 1, 6, cross7, text_color=color.white, bgcolor=color7)
table.cell(dashboard, 0, 7, "8 > 9", text_color=color.white, bgcolor=color8)
table.cell(dashboard, 1, 7, cross8, text_color=color.white, bgcolor=color8)
table.cell(dashboard, 0, 8, "9 > 10", text_color=color.white, bgcolor=color9)
table.cell(dashboard, 1, 8, cross9, text_color=color.white, bgcolor=color9)
table.cell(dashboard, 0, 9, "10 > 11", text_color=color.white, bgcolor=color10)
table.cell(dashboard, 1, 9, cross10, text_color=color.white, bgcolor=color10)
table.cell(dashboard, 0, 10, "11 > 12", text_color=color.white, bgcolor=color11)
table.cell(dashboard, 1, 10, cross11, text_color=color.white, bgcolor=color11)
table.cell(dashboard, 0, 11, "12 > 13", text_color=color.white, bgcolor=color12)
table.cell(dashboard, 1, 11, cross12, text_color=color.white, bgcolor=color12)
table.cell(dashboard, 0, 12, "13 > 14", text_color=color.white, bgcolor=color13)
table.cell(dashboard, 1, 12, cross13, text_color=color.white, bgcolor=color13)
table.cell(dashboard, 0, 13, "14 > 15", text_color=color.white, bgcolor=color14)
table.cell(dashboard, 1, 13, cross14, text_color=color.white, bgcolor=color14)

table.cell(dashboard, 0, 15, "9 > 20", text_color=color.white, bgcolor=colorshort)
table.cell(dashboard, 1, 15, crossshort, text_color=color.white, bgcolor=colorshort)
table.cell(dashboard, 0, 16, "20 > 50", text_color=color.white, bgcolor=colorminidum)
table.cell(dashboard, 1, 16, cross20, text_color=color.white, bgcolor=colorminidum)
table.cell(dashboard, 0, 17, "50 > 200", text_color=color.white, bgcolor=colorlong)
table.cell(dashboard, 1, 17, cross50, text_color=color.white, bgcolor=colorlong)